services:
  minio:
    image: minio/minio:latest
    container_name: calcpad-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: calcpad-admin
      MINIO_ROOT_PASSWORD: calcpad-password-123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  calcpad-api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: calcpad-api
    ports:
      - "5159:5159"
    volumes:
      - ./CalcpadServer.Api:/app
      - calcpad-db:/app/data
    working_dir: /app
    command: dotnet run --urls "http://0.0.0.0:5159"
    depends_on:
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  minio-data:
    driver: local
  calcpad-db:
    driver: local